### PR TITLE
#494 issue fixed forgot password 

### LINKED ISSUE #494: Forgot password feature doesn't work

### PR DESCRIPTION
**Pull request by Harshawardhan-Kamble**
## Related Issue

Fixes #494 Forgot password feature implemented

## Changes Made

- [x] Added ForgotPassword.jsx component with email input and OTP sending functionality
- [x] Enhanced OtpInput.jsx to handle both signup and password reset OTP verification flows
- [x] Implemented ResetPassword.jsx component for secure password reset with strength validation
 
 Added backend endpoints:
- [x] POST /auth/forgot-password - Send OTP to user's email
- [x] POST /auth/verify-reset-otp - Verify OTP and generate reset token
- [x] POST /auth/reset-password - Reset password with verified token

- [x] Enhanced email service to support different email types (signup/reset)

## Screenshots or GIFs (if applicable)

https://github.com/user-attachments/assets/0763396f-9aed-468c-b70b-38a13424f56b

## Checklist
- [x] I have performed a self-review of my code.
- [x] My changes are well-documented.
- [ ] I have added tests that prove my fix is effective or that my feature works.
- [ ] Any dependent changes have been merged and published.

### CODE REVIEW

File: Client/src/Auth/ResetPassword.jsx [hunk 1]
```diff
@@ -0,0 +1,362 @@
...
+    try {
+       const resetToken = localStorage.getItem("resetToken");
+      if (!resetToken) {
+        toast.error("Reset token not found. Please start the process again.");
+        navigate("/forgot-password");
+        return;
+      }
+
+      const url = `${backendUrl}/auth/reset-password`;
+      const response = await axiosInstance.post(
```
Comment (Shitanshukumar607) [inline Client/src/Auth/ResetPassword.jsx:124]: @Harshawardhan-Kamble you dont need the `${backendUrl}` here you can simply do 
`axiosInstance.post("/auth/reset-password" , ....`

File: Client/src/Auth/ForgotPassword.jsx [hunk 2]
```diff
@@ -0,0 +1,255 @@
...
+    register,
+    handleSubmit,
+    formState: { errors, isSubmitting },
+    getValues,
+  } = useForm();
+
+  const onSubmit = async (data) => {
+    try {
+      const url = `${backendUrl}/auth/forgot-password`;
+      const response = await axiosInstance.post(url, { Email: data.Email });
```
Comment (Shitanshukumar607) [inline Client/src/Auth/ForgotPassword.jsx:66]: same here

File: Client/src/Auth/ResetPassword.jsx (hunk 1 above)
Comment (Harshawardhan-Kamble) [reply Client/src/Auth/ResetPassword.jsx:124]: Thanks for pointing out will change

File: Client/src/Auth/ForgotPassword.jsx (hunk 2 above)
Comment (Harshawardhan-Kamble) [reply Client/src/Auth/ForgotPassword.jsx:66]: Changing

File: Client/src/Auth/ResetPassword.jsx (hunk 1 above)
Comment (Harshawardhan-Kamble) [reply Client/src/Auth/ResetPassword.jsx:124]: Done

**Comment by RishuKumarCodes** [comment]
@Harshawardhan-Kamble changes looks good, can you confirm if your changes fulfil this condition?
- The user logged-in with Google, mustn't be able to change their password (because user didn't set his password while he logged-in. It can be checked if user have logged-in from Google. 

Also, this step seems unnecessary, you can directly redirect to entering OTP. 
image

**Comment by amandollar** [comment]
@Harshawardhan-Kamble, please resolve the conflicts.

**Comment by Harshawardhan-Kamble** [comment]
resolved conflicts @amandollar

**Comment by amandollar** [comment]
@Harshawardhan-Kamble merging it
