### PR TITLE
Fix the issues in search functionality of chat

### LINKED ISSUE #830: Fixing search bar on chats page
Editing the functionality of the search bar on chat page

### PR DESCRIPTION
**Pull request by paramjeet-dev**
## Description
Properly handled the search bar functionality as per the issue.

## Related Issue
Fixes #830 

## Changes Made
- Adeed `Client/src/api/userApi.js` added for fetching all users in frontend
- Updated `Client/src/components/chats/userlist.tsx`
- Updated `Client/src/pages/Chats.jsx`
- Added `Client/src/queries/userQueries.js` for fetching backend
- Updated `Server/Controller/UserController.js`
- Updated `Server/Routes/UserRoutes.js`

## Screenshots or GIFs (if applicable)
Screenshot 2025-09-23 200139
Screenshot 2025-09-23 200129
Screenshot 2025-09-23 200115

## checklist

- [x] Code is formatted with the project’s Prettier config provided in `.prettierrc`.
- [x] Only the necessary files are modified; no unrelated changes are included.
- [x] Follows clean code principles (readable, maintainable, minimal duplication).
- [x] All changes are clearly documented.
- [x] Code has been tested across all supported themes and verified against potential edge cases.
- [x] Multiple screenshots or recordings are attached (if required).
- [x] No breaking changes are introduced to existing functionality.

### CODE REVIEW

File: Server/Controller/UserController.js [hunk 1]
```diff
@@ -247,10 +247,36 @@ const giveKudos = async (req, res) => {
   }
 };
 
+const getAllUsers = async (req, res) => {
```
Comment (RishuKumarCodes) [inline Server/Controller/UserController.js:250]: @paramjeet-dev your changes look well structured, but the name of this function could be confusing. Instead, you can name it `findUser`  or `findUserByUsernameOrEmail` as it doesn't return all the users.

File: Server/Routes/UserRoutes.js [hunk 2]
```diff
@@ -83,4 +84,6 @@ router.post(
   uploadProfilePicture
 );
 
+router.get("/", getAllUsers);
```
Comment (RishuKumarCodes) [inline Server/Routes/UserRoutes.js:87]: also the backend endpoint as `/` could be confusing.

File: Server/Controller/UserController.js (hunk 1 above)
Comment (paramjeet-dev) [reply Server/Controller/UserController.js:250]: Ok

Comment (paramjeet-dev) [reply Server/Controller/UserController.js:250]: done
